CREATE TABLE MEMBERS(
    MEMBER_ID VARCHAR2(50) PRIMARY KEY,
    MEMBER_PASSWORD VARCHAR2(50) NOT NULL,
    MEMBER_NAME VARCHAR2(50) NOT NULL,
    MEMBER_AGE NUMBER NOT NULL,
    MEMBER_ADDRESS VARCHAR2(100) NOT NULL,
    MEMBER_POINT NUMBER NOT NULL,
    MEMBER_GENRE VARCHAR2(50) NOT NULL
    );


CREATE TABLE BOOKS(
    BOOK_ID VARCHAR2(50)PRIMARY KEY,
    BOOK_STOCK NUMBER NOT NULL,
    BOOK_NAME VARCHAR2(50) NOT NULL,
    BOOK_PRICE NUMBER NOT NULL,
    BOOK_RENTALPRICE NUMBER NOT NULL,
    BOOK_AUTHOR VARCHAR2(50) NOT NULL,
    BOOK_PUBLISHER VARCHAR2(50) NOT NULL
    );


CREATE TABLE RENTED_BOOKS(
    RENT_MEMBER_ID VARCHAR2(50) NOT NULL,
    RENT_BOOK_ID VARCHAR2(50) NOT NULL,
    RENT_RENTED_DATE DATE NOT NULL,
    RENT_RETURN_DATE DATE NOT NULL
    );

CREATE TABLE QNAS(
    QNA_NUM NUMBER PRIMARY KEY NOT NULL,
    QNA_SUBJECT VARCHAR2(50) NOT NULL,
    QNA_CONTENT VARCHAR2(2000) NOT NULL,
    QNA_DATE DATE NOT NULL,
    QNA_CLICKED_COUNT NUMBER NOT NULL,
    QNA_FILE VARCHAR2(50) NOT NULL,
    QNA_RE_REF NUMBER NOT NULL,
    QNA_RE_LEV NUMBER NOT NULL,
    QNA_RE_STEP NUMBER NOT NULL
    );

    
CREATE TABLE REVIEWS(
    REVIEW_NUM NUMBER PRIMARY KEY NOT NULL,
    REVIEW_SUBJECT VARCHAR2(50) NOT NULL,
    REVIEW_CONTENT VARCHAR2(2000) NOT NULL,
    REVIEW_DATE DATE NOT NULL,
    REVIEW_CLICKED_COUNT NUMBER NOT NULL,
    REVIEW_FILE VARCHAR2(50) NOT NULL
    );    
    

CREATE TABLE NOTICES(
    NOTICE_NUM NUMBER PRIMARY KEY NOT NULL,
    NOTICE_SUBJECT VARCHAR2(50) NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000) NOT NULL,
    NOTICE_DATE DATE NOT NULL,
    NOTICE_CLICKED_COUNT NUMBER NOT NULL,
    NOTICE_FILE VARCHAR2(50) NOT NULL
    );

SELECT * FROM MEMBERS;
--문학, 자기계발, 과학
--도서ID, 재고, 책이름, 책가격, 대여비용, 저자, 출판사
SELECT * FROM BOOKS;
INSERT INTO BOOKS VALUES('100-001', 1, '해리 포터와 마법사의 돌', 10050, 500, 'J.K. Rowling', 'Pottermore from J.K. Rowling');
INSERT INTO BOOKS VALUES('100-002', 1, '라이프 리스트', 14800, 500, '로리 넬슨 스필먼', '나무옆의자');
INSERT INTO BOOKS VALUES('100-003', 1, '왜 나는 너를 사랑하는가', 12000, 500, '알랭 드 보통', '청미래');
INSERT INTO BOOKS VALUES('200-001', 1, '무조건 달라진다', 16000, 500, '션영', '21세기북스');
INSERT INTO BOOKS VALUES('200-002', 1, '심리학이 이렇게 쓸모 있을 줄이야', 13000, 500, '류쉬안', '다연');
INSERT INTO BOOKS VALUES('200-003', 1, '나는 회사 다니면서 공부하기로 했다', 14000, 500, '사토 다카유키', '리더스북');
INSERT INTO BOOKS VALUES('300-001', 1, '과학혁명의 구조', 18000, 500, '토머스 S.쿤', '까치');
INSERT INTO BOOKS VALUES('300-002', 1, '살아있는 에너지(신과학총서 2)', 18000, 500, '콜럼 코츠', '양문');
INSERT INTO BOOKS VALUES('300-003', 1, '물리학자는 영화에서 과학을 본다', 15000, 500, '정재승', '어크로스');
